- name: Install Nginx
  apt:
    name: "{{ nginx_name }}"
    state: latest

- name: Nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
  notify:
    - reload nginx

- name: Ensure Nginx is running
  service:
    name: "{{ nginx_name }}"
    state: started
    enabled: yes
